version: 2

models:

  - name: country_map_data
    description: >
      Reference table containing geographical mapping data for countries and regions,
      including standardized codes, names, and hierarchical relationships. This table
      serves as a master reference for country-level analytics and reporting.


  - name: latest_state_data
    description: >
      Consolidated view of the most recent state-level metrics and indicators,
      providing a current snapshot of key economic and demographic measures for
      each state. Updated daily with the latest available data points.
