name: "dbt_project"
version: "1.0.0"
config-version: 2

profile: "econ_database"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won"t need to change these!
model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]


target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  +materialized: table