name: "dbt_project"
version: "1.0.0"
config-version: 2
profile: "econ_database"

# Directory configurations
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

# Model configurations
models:
  dbt_project: 
    +materialized: table

# Package configurations
packages:
  - package: dbt-labs/dbt_utils
    version: 1.1.1
  - package: duckdb/dbt-duckdb
    version: 1.9.2