version: 2

models:
  - name: market_economic_analysis
    description: >
      Combines market return analysis tables (currency, fixed income, global markets, major indices, US sectors) with government economic indicators to provide a comprehensive view of the relationship between economic changes and forward market returns. This model enables analysis of how macroeconomic factors such as GDP, inflation, interest rates, employment, producer prices, industrial production, and housing impact future market performance. It includes lagged economic changes, regime classification, and composite economic stress indicators for advanced economic and market research.
