version: 2

models:
  - name: market_economic_analysis
    description: >
      Combines market return analysis tables (currency, fixed income, global markets, major indices, US sectors) with government economic indicators to provide a comprehensive view of the relationship between economic changes and forward market returns. This model enables analysis of how macroeconomic factors such as GDP, inflation, interest rates, employment, producer prices, industrial production, and housing impact future market performance. It includes lagged economic changes, regime classification, and composite economic stress indicators for advanced economic and market research.
    columns:
      - name: year_month
        tests:
          - not_null
      - name: month_date
        tests:
          - not_null

  - name: base_historical_analysis
    description: >
      Comprehensive historical analysis combining market return data across all asset categories (currency, fixed income, global markets, major indices, and US sectors) with economic indicators from FRED. This model provides a unified view of market performance metrics including monthly and quarterly averages, forward-looking percentage changes, and corresponding economic data points. Enables cross-asset analysis and correlation studies between market returns and economic indicators.
    columns:
      - name: symbol
        description: "Trading symbol for the financial instrument"
        tests:
          - not_null
      - name: month_date
        description: "First day of the month for the data point"
        tests:
          - not_null
      - name: quarter_num
        description: "Quarter number (1-4) for the data point"
      - name: year_val
        description: "Year for the data point"
      - name: monthly_avg_close
        description: "Average closing price for the month"
      - name: monthly_avg_volume
        description: "Average trading volume for the month"
      - name: quarterly_avg_close
        description: "Average closing price for the quarter"
      - name: quarterly_avg_volume
        description: "Average trading volume for the quarter"
      - name: pct_change_q1_forward
        description: "Percentage change from current quarter to Q1 forward"
      - name: pct_change_q2_forward
        description: "Percentage change from current quarter to Q2 forward"
      - name: pct_change_q3_forward
        description: "Percentage change from current quarter to Q3 forward"
      - name: pct_change_q4_forward
        description: "Percentage change from current quarter to Q4 forward"
      - name: category
        description: "Asset category: currency, fixed_income, global_markets, major_indicies, or sector"
        tests:
          - not_null
          - accepted_values:
              values: ['currency', 'fixed_income', 'global_markets', 'major_indicies', 'sector']
      - name: series_name
        description: "Name of the FRED economic series"
      - name: value
        description: "Value of the economic indicator"
      - name: period_diff
        description: "Period-over-period difference in the economic indicator value"

  - name: leading_econ_return_indicator
    description: >
      Analysis of economic data rate of change vs future stock returns, providing correlation analysis and quintile performance insights
    columns:
      - name: symbol
        tests:
          - not_null
      - name: series_name
        tests:
          - not_null
      - name: analysis_type
        tests:
          - not_null
      - name: economic_category
        tests:
          - not_null
