version: 2

sources:
  - name: fred_data
    tables:
      - name: fred_data_raw
        meta:
          dagster:
            asset_key: ["fred_data_raw"]
  - name: bls_data
    tables:
      - name: housing_inventory_raw
        meta:
          dagster:
            asset_key: ["housing_inventory_raw"]
      - name: housing_pulse_raw
        meta:
          dagster:
            asset_key: ["housing_pulse_raw"]
  - name: realtor_data_raw
    tables:
      - name: RDC_Inventory_Core_Metrics_Country_History
        meta:
          dagster:
            asset_key: ["RDC_Inventory_Core_Metrics_Country_History"]
      - name: RDC_Inventory_Core_Metrics_County_History
        meta:
          dagster:
            asset_key: ["RDC_Inventory_Core_Metrics_County_History"]
      - name: RDC_Inventory_Core_Metrics_Metro_History
        meta:
          dagster:
            asset_key: ["RDC_Inventory_Core_Metrics_Metro_History"]
      - name: RDC_Inventory_Core_Metrics_Zip_History
        meta:
          dagster:
            asset_key: ["RDC_Inventory_Core_Metrics_Zip_History"]
      - name: RDC_Inventory_Core_Metrics_State_History
        meta:
          dagster:
            asset_key: ["RDC_Inventory_Core_Metrics_State_History"]