version: 2

sources:
  - name: staging
    schema: main
    tables:
      # FRED Data
      - name: fred_raw

        
      # Housing Data
      - name: housing_inventory_raw

      - name: housing_pulse_raw
      # Treasury Yields Data
      - name: treasury_yields_raw